### ISSUE TITLE
A typo on the main plot and poincare_mean implementation

### ISSUE THREAD

**Issue by ferrine** [KhrulkovV/hyperbolic-image-embeddings#1]
in
https://github.com/KhrulkovV/hyperbolic-image-embeddings/blob/master/hyptorch/pmath.py#L426
you use
https://github.com/KhrulkovV/hyperbolic-image-embeddings/blob/master/hyptorch/pmath.py#L106
but should
```python
def lorenz_factor(x, *, c=1.0, dim=-1, keepdim=False):
    """

    Parameters
    ----------
    x : tensor
        point on Klein disk
    c : float
        negative curvature
    dim : int
        dimension to calculate Lorenz factor
    keepdim : bool
        retain the last dim? (default: false)

    Returns
    -------
    tensor
        Lorenz factor
    """
    return 1 / torch.sqrt(1 - c * x.pow(2).sum(dim=dim, keepdim=keepdim))
```
Also the comment on 
![image](https://user-images.githubusercontent.com/11705326/56084108-f6995680-5e36-11e9-9460-3499b281255b.png)
And the point `HypAvg(x, y)` should probably be `HypAvg(x, y, z)`. `HypAvg(x, y)` should correspond to `pmath.geodesic(.5, x, y)`

**Comment by KhrulkovV** [comment]
Thank you very much, there was indeed a bug, fixed now. I will update the image a bit later.
