### ISSUE TITLE
Code to calculate the hyperbolicity of image datasets

### ISSUE THREAD

**Issue by AdarshMJ** [KhrulkovV/hyperbolic-image-embeddings#10]
Hi! Excellent work! Thank you for releasing the codebase. I wanted to know how to calculate the hyperbolicity of the image datasets (section 3.1 in the paper). I can see a delta.py file in the codebase but no instructions on how to use this. Any help would be appreciated. Thanks in advance!

**Comment by vak** [comment]
`get_delta()` isn't called from anywhere and
`delta_hyp()` uses only first row/column only somehow strange (variable `p` is set to 0 and never changed)

**Comment by GasserElbanna** [comment]
@AdarshMJ did you manage to run it properly? I am trying to test it on audio-related datasets but the results are pretty weird.

**Comment by leymir** [comment]
This function isn't supposed to be called from anywhere, the goal is just to calculate the delta value itself (as in article). The function input is a distance matrix: for visual data it is calculated for features extracted from images. I think, for audio-related datasets you can use any reasonable features, calculate the matrix of distances between them and plug it into delta_hyp function.
