### ISSUE TITLE
Calculating Hyperbolicity bug in delta.py?

### ISSUE THREAD

**Issue by ajbanks** [KhrulkovV/hyperbolic-image-embeddings#12]
I have tried to reproduce your hyperbolicity experiments with the cifar10 dataset, using the code in delta.py. I have stumbled across a potential error. In the paper you calculate the relative Hyperbolicity of a dataset by doing the following calculation:

`δrel(X) = 2δ(X) / diam(X)`

However, in the delta.py δ(X) is not multiplied by 2, giving incorrect results:
`delta_rel = delta_hyp(distmat) / diam`

When I multiply by 2 it seems to work and I can reproduce the cifar10 hyperbolicity score:

`delta_rel = (2 * delta_hyp(distmat)) / diam`

Is this change correct?

**Comment by leymir** [comment]
Hello, thank you for pointing this out. The correct formula is given in the paper, I'll fix the code.
