### ISSUE TITLE
Can't achieve the accuracy as reported in the paper.

### ISSUE THREAD

**Issue by xionghc** [KhrulkovV/hyperbolic-image-embeddings#2]
I followed the instruction to run this code, but I can't achieve the accuracy as reported in the paper.  As shown in instructions, `python train_protonet.py --gpu 0 --hyperbolic --dataset MiniImageNet --dim 1024 --lr 0.001 --c 0.05 --gamma 0.2 --step_size 10` was used at my experiments, the accuracy can only achieve 43.92%, it is a lot behind 51.57% that shown in the paper.

**Comment by KhrulkovV** [comment]
Hey, try the following
`python train_protonet.py --gpu 0 --hyperbolic --dataset MiniImageNet --dim 1024 --lr 0.001 --c 0.05 --gamma 0.2 --step_size 10 --way 30`
This sets way to be 30 during training, which helps a lot.

**Comment by xionghc** [comment]
That's ok. Thanks.
