### ISSUE TITLE
Hyperbolic CNN

### ISSUE THREAD

**Issue by ruoshiliu** [KhrulkovV/hyperbolic-image-embeddings#6]
Thanks for sharing your great work! Since the hyperbolic neural network is pretty well-defined and I imagine building convolution layers won't be too difficult (correct me if I'm wrong), I was wondering if you guys experimented with building a fully hyperbolic CNN? Can you please share your thoughts regarding that?

**Comment by KhrulkovV** [comment]
Hey @ruoshiliu, sorry for a late response. Yes, this is possible to do (by simply wrapping convolutional layers between `ToPoincare` and `FromPoincare` layers, but as fas as I know this does not lead to any particularly good results. [Maxim](https://github.com/ferrine) was experimenting with it, so probably he is a better source of information on this.

**Comment by ruoshiliu** [comment]
I see. Performing feature extraction in hyperbolic space doesn't seem necessary to me either. Thanks for the insights and reference! Really appreciate it!
