### ISSUE TITLE
The values of '_mobius_add(-x, y, c).norm(dim=-1, p=2, keepdim=keepdim)' are ones

### ISSUE THREAD

**Issue by canqin001** [KhrulkovV/hyperbolic-image-embeddings#9]
Hi. This is a very interesting and inspiring work. I just use your code to my dataset for computing feature distance. I found that all the values of '_mobius_add(-x, y, c).norm(dim=-1, p=2, keepdim=keepdim' of the line 207 of './hyptorch/pmath.py' tend to be 1. Did you meet the same issue like this or have any suggestions? Thanks.

**Comment by KhrulkovV** [comment]
Hey!
Could you please provide more details? Did you map the features to the Poincare ball before computing the distance?

**Comment by canqin001** [comment]
Hi. I have fixed the bug:) Thanks for your reply!
